package entities;

import static org.junit.Assert.assertEquals;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import card.Card;
import card.Card.Builder;
import settings.AppConfig;
import settings.CardNumberGenerator;

import static settings.constants.ConfigProperty.FARE_PRECISION_SCALE;;

public class CardTest {

	private Card.Builder builder;

	@Before
	public void setUp() {
		AppConfig.INST.setProperty(FARE_PRECISION_SCALE, String.valueOf(2));

		builder = Builder.New();
	}

	@After
	public void tearDown() {
		builder = null;
		AppConfig.INST.removeProperty(FARE_PRECISION_SCALE);
	}

	@Test
	public void newCardCreatedCorrectlyIfBuiltWithNumberAndBalance() {
		Long number = CardNumberGenerator.INST.generate();
		Double amount = Double.valueOf(30.5d);

		Card newCard = builder
			.number(number)
			.balance(amount)
			.build();

		assertEquals(Boolean.TRUE, newCard.getBalance().equals(amount));
		assertEquals(Boolean.TRUE, newCard.getNumber().equals(number));
	}

	@Test
	public void autoGeneratedNumberIfProvidedWithBalanceOnly() {
		Double amount = Double.valueOf(30.5d);

		Card newCard = builder
			.balance(amount)
			.build();

		assertEquals(Boolean.TRUE, newCard.getBalance().equals(amount));
		assertEquals(Boolean.TRUE, null != newCard.getNumber());
	}
}
